-- INFO: Urgency-sorted task picker; tv.nvim (television) when available,
-- vim.ui.select otherwise.

local M = {}

local channel_toml = [==[
# Generated by tw-todo.nvim — pending taskwarrior tasks for the current project.
[metadata]
name = "tw-todo"
description = "tw-todo: pending taskwarrior tasks for this project"

# The script is POSIX, but television runs commands through $SHELL (which may
# be nushell/fish), so it is wrapped in an explicit `sh -c`.
[source]
command = '''sh -c 'p=$(d=$PWD; while [ "$d" != "/" ]; do for m in .tw-todo .git; do if [ -e "$d/$m" ]; then echo "$d"; break 2; fi; done; d=$(dirname "$d"); done); p=$(basename "${p:-$PWD}"); task rc.confirmation=off rc.verbose=nothing rc.uda.twhash.type=string rc.uda.twfile.type=string rc.uda.twissue.type=numeric rc.report.twtodo.columns=urgency,twhash,twfile,description.desc rc.report.twtodo.labels=,,, rc.report.twtodo.sort=urgency- "project:$p" status:pending twtodo 2>/dev/null' '''

[preview]
command = '''sh -c 'set -- {}; grep -n -B 3 -A 10 -- "$2" "$3"' '''
]==]

--- Write the television cable channel definition, refreshing it whenever the
--- bundled template changes (the file is fully owned by tw-todo).
function M.ensure_channel()
    local path = vim.fs.joinpath(vim.fn.expand("~/.config/television/cable"), "tw-todo.toml")
    local current = vim.uv.fs_stat(path) and table.concat(vim.fn.readfile(path), "\n") or nil
    if current == vim.trim(channel_toml) then
        return
    end
    vim.fn.mkdir(vim.fs.dirname(path), "p")
    vim.fn.writefile(vim.split(vim.trim(channel_toml), "\n"), path)
    vim.notify("tw-todo: installed television channel at " .. path, vim.log.levels.INFO)
end

--- Open the file of a picker entry and land on its hash line.
---@param hash string
---@param file string path relative to the project root
local function jump_to(hash, file)
    local root = require("tw-todo.task").project_root(0)
    local path = vim.fs.joinpath(root, file)
    if not vim.uv.fs_stat(path) then
        path = file -- twfile may be absolute for files outside the root
    end
    vim.cmd.edit(vim.fn.fnameescape(path))
    local prefix = require("tw-todo.config").options.hash_prefix
    if vim.fn.search(vim.fn.escape(prefix .. hash, "\\"), "w") > 0 then
        vim.cmd("normal! zz")
    end
end

--- tv.nvim <CR> handler: entries are report lines "urgency hash file desc...".
---@param entries string[]
function M.jump(entries)
    local entry = entries and entries[1]
    if not entry then
        return
    end
    local _, hash, file = entry:match("^%s*(%S+)%s+(%S+)%s+(%S+)")
    if hash and file then
        jump_to(hash, file)
    end
end

local registered = false
local function register_tv()
    local ok, tv = pcall(require, "tv")
    if not ok then
        return false
    end
    if not registered then
        require("tv.config").merge({
            channels = {
                ["tw-todo"] = {
                    args = { "--no-remote", "--no-status-bar" },
                    handlers = {
                        ["<CR>"] = function(entries)
                            M.jump(entries)
                        end,
                    },
                },
            },
        })
        registered = true
    end
    return true, tv
end

--- Fallback picker without tv.nvim.
local function ui_select()
    local task = require("tw-todo.task")
    task.export({ "project:" .. task.project_name(0), "status:pending" }, function(tasks)
        if #tasks == 0 then
            vim.notify("tw-todo: no pending tasks for this project", vim.log.levels.INFO)
            return
        end
        table.sort(tasks, function(a, b)
            return (a.urgency or 0) > (b.urgency or 0)
        end)
        vim.ui.select(tasks, {
            prompt = "tw-todo tasks (by urgency):",
            format_item = function(t)
                return ("%5.1f  %s (%s)"):format(t.urgency or 0, t.description, t.twfile or "?")
            end,
        }, function(t)
            if t and t.twhash and t.twfile then
                jump_to(t.twhash, t.twfile)
            end
        end)
    end)
end

--- Open the task picker.
function M.open()
    local ok, tv = register_tv()
    if ok then
        M.ensure_channel()
        tv.tv_channel("tw-todo")
    else
        ui_select()
    end
end

return M
